version: '3'

services:
    rides:
        container_name: rides
        image: rides:latest
        build: "./rideapp"
        ports: 
            - '8000:8000'
            # host:container
        expose:
            - "8000"
        depends_on:
            - ridedb
        networks:
            - users_ridesharenet

    ridedb:
        container_name: ridedb
        build: "./mongodb"
        ports:
            - '27018:27017'
        networks:
            - users_ridesharenet

networks:
    users_ridesharenet:
            external: true
