version: '3'
services:

    users:
        container_name: users
        image: users:latest
       
        build: "./userapp" 
     
        ports:
            - '8080:8080'
        # host:container
        expose:
            - "8080"
        depends_on:
            - userdb
        networks:
            - ridesharenet

    userdb:
        # not pulling the actual mongo image here. look in docker file
        container_name: userdb
        
        build: "./mongodb"

        ports:
            - '27017:27017'
        networks:
            - ridesharenet

networks:
        ridesharenet:
            driver: bridge
