version: '3'
services:
    users:
        build:
            context: .docker-compose up -d
            dockerfile: Dockerfile
        container_name: usercontainer
        ports:
            - "80:8080" # host:container
        expose: 
            - "8080"
        # volumes:
        #  - .:/project
        depends_on:
            - usersdb
    usersdb:
        image: "mongo"
        container_name: mongousers
        command: mongod
        expose:
            - "27017"